use_frameworks!

target 'RxWatchConnectivity_Example' do
  pod 'RxWatchConnectivity', :path => '../'

  target 'RxWatchConnectivity_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
